"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Header from "@/components/layout/Header";
import { fetchApi } from "@/lib/api";
type Schedule = { id:number; title:string; module_code:string; schedule_type:string; line_name?:string; equipment?:string; start_at:string; end_at?:string; status:string; assigned_to?:string; impact?:string; work_scope?:string; remarks?:string };
const empty = { title:"", module_code:"ALL", schedule_type:"PM_OFFLINE", line_name:"", equipment:"", start_at:"", end_at:"", status:"PLANNED", assigned_to:"", impact:"", work_scope:"", remarks:"" };
const fmt=(s?:string)=>s?new Date(s).toLocaleString():"Not specified";
export default function MaintenanceSchedulePage(){
 const [rows,setRows]=useState<Schedule[]>([]),[form,setForm]=useState({...empty}),[filter,setFilter]=useState("ALL"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const load=useCallback(async()=>{try{setError("");const result=await fetchApi("/maintenance-schedules?module="+filter);setRows(result.schedules||[])}catch(e:any){setError(e.message||"Could not load schedule")}},[filter]);
 useEffect(()=>{load()},[load]);
 const counts=useMemo(()=>({planned:rows.filter(x=>["PLANNED","APPROVED"].includes(x.status)).length,active:rows.filter(x=>x.status==="IN_PROGRESS").length,completed:rows.filter(x=>x.status==="COMPLETED").length}),[rows]);
 function set<K extends keyof typeof empty>(key:K,value:string){setForm(p=>({...p,[key]:value}))}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setSuccess("");try{await fetchApi("/maintenance-schedules",{method:"POST",body:JSON.stringify({...form,end_at:form.end_at||null,line_name:form.line_name||null,equipment:form.equipment||null,assigned_to:form.assigned_to||null,impact:form.impact||null,work_scope:form.work_scope||null,remarks:form.remarks||null})});setForm({...empty});setSuccess("Maintenance window scheduled.");await load()}catch(e:any){setError(e.message||"Could not save schedule")}finally{setBusy(false)}}
 async function changeStatus(id:number,status:string){try{await fetchApi("/maintenance-schedules/"+id+"/status?status="+encodeURIComponent(status),{method:"PATCH"});await load()}catch(e:any){setError(e.message||"Could not update status")}}
 async function remove(id:number){if(!window.confirm("Delete this scheduled maintenance window?"))return;try{await fetchApi("/maintenance-schedules/"+id,{method:"DELETE"});await load()}catch(e:any){setError(e.message||"Could not delete schedule")}}
 return <div className="dsr-page"><Header title="Scheduled Maintenance"/><main className="dsr-main"><div className="full-bleed space-y-4">
 <div className="dsr-section-head"><div><div className="dsr-kicker">Plant-wide planning</div><h1 className="dsr-title">Maintenance Schedule</h1><p className="dsr-subtitle">Plan PM offline windows, belt changes and shutdown work across DSIR, RMIR, MIR, DIR and SSIR. This is a shared register visible from every module.</p></div></div>
 <div className="grid grid-cols-1 gap-3 sm:grid-cols-3"><div className="mechanical-panel p-4"><div className="helper-text">Planned / approved</div><div className="text-2xl font-semibold">{counts.planned}</div></div><div className="mechanical-panel p-4"><div className="helper-text">In progress</div><div className="text-2xl font-semibold">{counts.active}</div></div><div className="mechanical-panel p-4"><div className="helper-text">Completed</div><div className="text-2xl font-semibold">{counts.completed}</div></div></div>
 <section className="mechanical-panel overflow-hidden"><div className="dsr-panel-head"><div><div className="section-title">Plan a maintenance window</div><div className="helper-text">Choose ALL registers for plant shutdown work or one register for module-specific maintenance.</div></div></div>
 <form onSubmit={save} className="grid grid-cols-1 gap-3 p-4 md:grid-cols-3">
 <label className="text-sm">Work title<input required minLength={2} className="input-class mt-1" value={form.title} onChange={e=>set("title",e.target.value)} placeholder="e.g. WRM2 belt change"/></label>
 <label className="text-sm">Register<select className="input-class mt-1" value={form.module_code} onChange={e=>set("module_code",e.target.value)}>{["ALL","DSIR","RMIR","MIR","DIR","SSIR"].map(x=><option key={x}>{x}</option>)}</select></label>
 <label className="text-sm">Maintenance type<select className="input-class mt-1" value={form.schedule_type} onChange={e=>set("schedule_type",e.target.value)}>{[["PM_OFFLINE","PM offline"],["BELT_CHANGE","Belt change"],["SHUTDOWN","Shutdown"],["INSPECTION","Inspection"],["OVERHAUL","Overhaul"],["OTHER","Other"]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 <label className="text-sm">Line / area<input className="input-class mt-1" value={form.line_name} onChange={e=>set("line_name",e.target.value)} placeholder="e.g. WRM1 / WRM2 / WRM3"/></label>
 <label className="text-sm">Equipment / assets<input className="input-class mt-1" value={form.equipment} onChange={e=>set("equipment",e.target.value)} placeholder="Belt, drive, motor, stands…"/></label>
 <label className="text-sm">Responsible person / team<input className="input-class mt-1" value={form.assigned_to} onChange={e=>set("assigned_to",e.target.value)} placeholder="Team or owner"/></label>
 <label className="text-sm">Start date & time<input required type="datetime-local" className="input-class mt-1" value={form.start_at} onChange={e=>set("start_at",e.target.value)}/></label>
 <label className="text-sm">Expected finish<input type="datetime-local" className="input-class mt-1" value={form.end_at} onChange={e=>set("end_at",e.target.value)}/></label>
 <label className="text-sm">Initial status<select className="input-class mt-1" value={form.status} onChange={e=>set("status",e.target.value)}>{["PLANNED","APPROVED","IN_PROGRESS","COMPLETED","DEFERRED","CANCELLED"].map(x=><option key={x}>{x}</option>)}</select></label>
 <label className="text-sm md:col-span-3">Work scope / PM job list<textarea className="input-class mt-1 min-h-[75px]" value={form.work_scope} onChange={e=>set("work_scope",e.target.value)} placeholder="Belt change, inspection, bearing/coupling checks, lubrication, trial run…"/></label>
 <label className="text-sm md:col-span-3">Expected production / safety impact<textarea className="input-class mt-1" value={form.impact} onChange={e=>set("impact",e.target.value)} placeholder="Affected line, isolation needs, production impact, permits or dependencies"/></label>
 <label className="text-sm md:col-span-3">Remarks<textarea className="input-class mt-1" value={form.remarks} onChange={e=>set("remarks",e.target.value)} placeholder="Parts readiness, coordination, follow-up"/></label>
 <div className="md:col-span-3"><button disabled={busy} className="dsr-btn-primary">{busy?"Saving…":"Save maintenance plan"}</button></div>
 </form></section>
 {error&&<div className="rounded-md border border-red-900 bg-red-950/20 p-3 text-red-300">{error}</div>}{success&&<div className="rounded-md border border-emerald-900 p-3 text-emerald-300">{success}</div>}
 <section className="mechanical-panel overflow-hidden"><div className="dsr-panel-head flex-wrap"><div><div className="section-title">Plant maintenance calendar</div><div className="helper-text">{rows.length} scheduled windows · newest start date first</div></div><select className="input-class max-w-[180px]" value={filter} onChange={e=>setFilter(e.target.value)}>{["ALL","DSIR","RMIR","MIR","DIR","SSIR"].map(x=><option key={x}>{x}</option>)}</select></div>
 <div className="dsr-table-wrap border-0 rounded-none"><table className="dsr-table"><thead><tr>{["Start / finish","Register","Type","Line / equipment","Planned work","Owner","Status","Actions"].map(x=><th key={x} className="dsr-th">{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="dsr-td whitespace-nowrap">{fmt(r.start_at)}<div className="helper-text">Until {fmt(r.end_at)}</div></td><td className="dsr-td font-semibold">{r.module_code}</td><td className="dsr-td">{r.schedule_type.replaceAll("_"," ")}</td><td className="dsr-td">{r.line_name||"—"}<div>{r.equipment||"—"}</div></td><td className="dsr-td min-w-[220px]"><b>{r.title}</b><div className="helper-text whitespace-pre-wrap">{r.work_scope||r.impact||r.remarks||"No scope entered"}</div></td><td className="dsr-td">{r.assigned_to||"—"}</td><td className="dsr-td">{r.status}</td><td className="dsr-td"><div className="flex flex-wrap gap-1">{r.status!=="IN_PROGRESS"&&r.status!=="COMPLETED"&&<button className="dsr-btn" onClick={()=>changeStatus(r.id,"IN_PROGRESS")}>Start</button>}{r.status!=="COMPLETED"&&<button className="dsr-btn" onClick={()=>changeStatus(r.id,"COMPLETED")}>Complete</button>}{r.status!=="DEFERRED"&&<button className="dsr-btn" onClick={()=>changeStatus(r.id,"DEFERRED")}>Defer</button>}<button className="dsr-btn" onClick={()=>remove(r.id)}>Delete</button></div></td></tr>)}{!rows.length&&<tr><td colSpan={8} className="dsr-empty">No scheduled maintenance windows. Add a plan above.</td></tr>}</tbody></table></div></section>
 </div></main></div>
}
