"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { Home, Wrench, Factory, Package, History, Users, LogIn, LogOut, ClipboardPaste, Database, BrainCircuit, ChevronDown, ChevronRight, FileText, Menu, X, Settings2, ServerCog, CalendarDays, Cpu, Zap, Cog } from "lucide-react";
import { AuthUser, clearSession, getUser, isAdmin } from "@/lib/auth";

export default function Sidebar(){
 const pathname=usePathname(); const router=useRouter(); const [user,setUser]=useState<AuthUser|null>(null); const [manageOpen,setManageOpen]=useState(false); const [mobileOpen,setMobileOpen]=useState(false);
 useEffect(()=>{const sync=()=>setUser(getUser());sync();window.addEventListener("dsr-auth-change",sync);window.addEventListener("storage",sync);return()=>{window.removeEventListener("dsr-auth-change",sync);window.removeEventListener("storage",sync)}},[]);
 useEffect(()=>{setMobileOpen(false);if(["/entry-guides","/reports","/import-report","/historical-import","/users","/planning","/system-status"].includes(pathname))setManageOpen(true)},[pathname]);
 const primary=[{name:"Home",href:"/dashboard",icon:Home}];
 const dsir=[{name:"Running Stand",href:"/running-stands",icon:Gauge},{name:"Stand Area",href:"/stand-area",icon:Factory},{name:"Stand Change",href:"/operations",icon:Wrench},{name:"Entry Guide Change",href:"/entry-guides",icon:Settings2},{name:"Spare Life",href:"/inventory",icon:Package},{name:"Maintenance Data",href:"/pm-schedule",icon:CalendarDays},{name:"AI / Intelligence",href:"/intelligence",icon:BrainCircuit},{name:"Alerts",href:"/alerts",icon:Zap},{name:"History",href:"/activity",icon:History},{name:"Export History",href:"/reports",icon:FileText} ,{name:"Import Report",href:"/import-report",icon:ClipboardPaste},{name:"Historical Data",href:"/historical-import",icon:Database}];
 const rmir=[{name:"Running Stand",href:"/rmir",icon:Gauge},{name:"Stand Area",href:"/rmir/stand-area",icon:Factory},{name:"Stand Change",href:"/rmir/stand-change",icon:Wrench},{name:"Entry Guide Change",href:"/rmir/entry-guide-change",icon:Settings2},{name:"Spare Life",href:"/rmir/spare-life",icon:Package},{name:"Maintenance Data",href:"/rmir/maintenance",icon:CalendarDays},{name:"AI / Intelligence",href:"/rmir/intelligence",icon:BrainCircuit},{name:"History",href:"/rmir/history",icon:History}];
 const mir=[{name:"Running Status",href:"/mir",icon:Gauge},{name:"Issues",href:"/mir/issues",icon:Zap},{name:"Maintenance Data",href:"/mir/maintenance",icon:CalendarDays},{name:"AI / Intelligence",href:"/mir/intelligence",icon:BrainCircuit},{name:"History",href:"/mir/history",icon:History}];
 const dir=[{name:"Running Status",href:"/dir",icon:Gauge},{name:"Alerts",href:"/dir/alerts",icon:Zap},{name:"Maintenance Data",href:"/dir/maintenance",icon:CalendarDays},{name:"History",href:"/dir/history",icon:History}];
 const ssir=[{name:"Running Status",href:"/ssir",icon:Gauge},{name:"Alerts",href:"/ssir/alerts",icon:Zap},{name:"Maintenance Data",href:"/ssir/maintenance",icon:CalendarDays},{name:"AI / Intelligence",href:"/ssir/intelligence",icon:BrainCircuit},{name:"History",href:"/ssir/history",icon:History}];
 const manage=pathname.startsWith("/rmir")?rmir:pathname.startsWith("/mir")?mir:pathname.startsWith("/dir")?dir:pathname.startsWith("/ssir")?ssir:dsir;
 const moduleLabel=pathname.startsWith("/rmir")?"RMIR · Roughing Mill":pathname.startsWith("/mir")?"MIR · Motors":pathname.startsWith("/dir")?"DIR · Drives":pathname.startsWith("/ssir")?"SSIR · Screw Shafts":"DSIR · Finishing Mill";
 const active=(href:string)=>pathname===href||(href==="/intelligence"&&pathname==="/investigation");
 const item=(i:any)=>{const I=i.icon;return <Link key={i.href} href={i.href} className={`nav-item ${active(i.href)?"nav-item-active":""}`}><I className={`w-4 h-4 shrink-0 ${active(i.href)?"text-[#4EA1FF]":"text-slate-500"}`}/><span>{i.name}</span></Link>};
 const logout=()=>{clearSession();setUser(null);router.push("/dashboard")};
 const panel=<><div><div className="brand-lockup"><div className="brand-mark"><span/></div><div><div className="brand-title">Asset Tracking Intelligence</div><div className="brand-subtitle">Plant-wide maintenance</div></div></div><div className="nav-label">Platform</div><nav className="space-y-1">{primary.map(item)}</nav><div className="nav-label mt-5">{moduleLabel}</div><nav className="space-y-1">{manage.map(item)}</nav></div><div className="sidebar-account">{user?<><div className="px-2 mb-2"><div className="text-sm font-semibold text-slate-100">{user.username}</div><div className="text-xs text-slate-400">{user.role==="ADMIN"?"Administrator":"Operator"}</div></div><button onClick={logout} className="account-action"><LogOut className="w-4 h-4"/>Sign out</button></>:<Link href="/login" className="account-action text-sky-300"><LogIn className="w-4 h-4"/>Sign in to edit</Link>}</div></>;
 return <><aside className="desktop-sidebar">{panel}</aside><header className="mobile-topbar"><button aria-label="Open navigation" onClick={()=>setMobileOpen(true)} className="mobile-menu-btn"><Menu className="w-5 h-5"/></button><div><div className="text-sm font-semibold text-white">Asset Tracking Intelligence</div><div className="text-xs text-slate-400">Plant-wide maintenance</div></div></header>{mobileOpen&&<div className="mobile-nav-overlay" onClick={()=>setMobileOpen(false)}><aside className="mobile-drawer" onClick={e=>e.stopPropagation()}><button aria-label="Close navigation" onClick={()=>setMobileOpen(false)} className="drawer-close"><X className="w-5 h-5"/></button>{panel}</aside></div>}<nav className="mobile-bottom-nav">{primary.slice(0,6).map(i=>{const I=i.icon;return <Link key={i.href} href={i.href} className={`mobile-nav-item ${active(i.href)?"text-[#4EA1FF]":""}`}><I className="w-5 h-5"/><span>{i.name.split("·")[0].trim()}</span></Link>})}</nav></>;
}
