"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Header from "@/components/layout/Header";
import { fetchApi } from "@/lib/api";

type EventRow = {id?:number;module_code:string;event_at:string|null;line_name?:string|null;position_number?:number|null;stand_code?:string|null;asset_code?:string|null;equipment?:string|null;component_type?:string|null;event_type:string;failure_mode?:string|null;symptoms?:string|null;suspected_cause?:string|null;confirmed_cause?:string|null;action_taken?:string|null;part_removed?:string|null;part_installed?:string|null;downtime_minutes?:number|null;operating_hours?:number|null;source_text?:string|null;ai_summary?:string|null;ai_confidence?:number|null;verification_status?:string};
type ComponentRow={id?:number;module_code:string;line_name?:string|null;position_number?:number|null;stand_code?:string|null;asset_code?:string|null;component_type:string;component_side?:string|null;serial_number?:string|null;installed_on:string;removed_on?:string|null;life_days?:number;operating_hours_at_install?:number|null;operating_hours_at_removal?:number|null;observed_life_hours?:number|null;removal_reason?:string|null;condition_on_removal?:string|null;work_done?:string|null};
const modules=["ALL","DSIR","RMIR","MIR","DIR","SSIR"];
const componentTypes=["STAND","ROLL","ENTRY_GUIDE","GEARBOX","GB","COUPLER","MOTOR","FLOATING_SHAFT","COUPLER_MOTOR_SIDE","COUPLER_GB_SIDE","BEARING","OIL_SEAL","SLEEVE","SHAFT","SCREW_SHAFT","DRIVE","VFD","OTHER"];
const eventTypes=["BREAKDOWN","INSPECTION","REPAIR","COMPONENT_CHANGE","STAND_CHANGE","PM","OBSERVATION","OTHER"];
const today=()=>new Date().toISOString().slice(0,10);
const fmt=(v?:string|null)=>v?new Date(v).toLocaleString():"Date not recorded";
const blankComponent=()=>({module_code:"RMIR",line_name:"WRM1",position_number:"1",stand_code:"",asset_code:"",component_type:"GEARBOX",component_side:"",serial_number:"",installed_on:today(),removed_on:"",operating_hours_at_install:"",operating_hours_at_removal:"",removal_reason:"",condition_on_removal:"",work_done:""});
export default function ReliabilityPage(){
 const [module,setModule]=useState("RMIR");
 useEffect(()=>{const requested=new URLSearchParams(window.location.search).get("module")?.toUpperCase();if(requested&&modules.includes(requested))setModule(requested)},[]);
 const [line,setLine]=useState("ALL");
 const [message,setMessage]=useState("");
 const [provider,setProvider]=useState("");
 const [events,setEvents]=useState<EventRow[]>([]);
 const [components,setComponents]=useState<ComponentRow[]>([]);
 const [history,setHistory]=useState<EventRow[]>([]);
 const [lifeRows,setLifeRows]=useState<ComponentRow[]>([]);
 const [componentForm,setComponentForm]=useState(blankComponent());
 const [busy,setBusy]=useState(false);
 const [error,setError]=useState("");
 const [notice,setNotice]=useState("");
 const [query,setQuery]=useState("");
 const [question,setQuestion]=useState("");
 const [answer,setAnswer]=useState("");
 const [answerSources,setAnswerSources]=useState<any[]>([]);
 const load=useCallback(async()=>{try{setError("");const [ev,co]=await Promise.all([fetchApi("/reliability/events?module="+module+"&limit=500"),fetchApi("/reliability/components?module="+module)]);setHistory(ev.events||[]);setLifeRows(co.components||[])}catch(e:any){setError(e.message||"Could not load reliability history")}},[module]);
 useEffect(()=>{load()},[load]);
 const activeComponents=useMemo(()=>lifeRows.filter(c=>!c.removed_on),[lifeRows]);
 const shownHistory=useMemo(()=>history.filter(e=>{const hay=[e.line_name,e.stand_code,e.equipment,e.component_type,e.failure_mode,e.symptoms,e.action_taken,e.source_text].join(" ").toLowerCase();return (!query||hay.includes(query.toLowerCase()))&&(line==="ALL"||e.line_name?.toUpperCase()===line)}),[history,query,line]);
 const shownComponents=useMemo(()=>lifeRows.filter(c=>(line==="ALL"||c.line_name?.toUpperCase()===line)&&(!query||[c.stand_code,c.component_type,c.component_side,c.serial_number,c.removal_reason].join(" ").toLowerCase().includes(query.toLowerCase()))),[lifeRows,line,query]);
 function patchEvent(i:number,k:string,v:any){setEvents(p=>p.map((x,n)=>n===i?({...x,[k]:v}):x))}
 function patchComponent(i:number,k:string,v:any){setComponents(p=>p.map((x,n)=>n===i?({...x,[k]:v}):x))}
 async function analyse(){if(!message.trim())return;setBusy(true);setError("");setNotice("");try{const result=await fetchApi("/reliability/analyse",{method:"POST",body:JSON.stringify({text:message,module_code:module})});setEvents((result.events||[]).map((x:EventRow)=>({...x,module_code:module,event_at:x.event_at?String(x.event_at).slice(0,16):""})));setComponents((result.components||[]).map((x:ComponentRow)=>({...x,module_code:module})));setProvider(result.provider||"AI");setNotice("AI created a review draft. Verify dates, equipment and causes before saving.");}catch(e:any){setError(e.message||"AI analysis failed")}finally{setBusy(false)}}
 async function confirm(){setBusy(true);setError("");setNotice("");try{const result=await fetchApi("/reliability/confirm",{method:"POST",body:JSON.stringify({events:events.map(x=>({...x,event_at:x.event_at?new Date(x.event_at).toISOString():null})),components,source_text:message})});setNotice("Saved "+(result.saved_events?.length||0)+" event(s) and "+(result.saved_components?.length||0)+" component record(s). "+((result.skipped||[]).length?((result.skipped||[]).length+" record(s) need missing data: "+result.skipped.map((x:any)=>x.reason).join("; ")):""));setEvents([]);setComponents([]);await load()}catch(e:any){setError(e.message||"Could not save verified records")}finally{setBusy(false)}}
 async function askAgent(){if(!question.trim())return;setBusy(true);setError("");setAnswer("");try{const result=await fetchApi("/reliability/ask",{method:"POST",body:JSON.stringify({text:question,module_code:module})});setAnswer(result.answer||"No answer returned");setAnswerSources(result.sources||[])}catch(e:any){setError(e.message||"Reliability investigation failed")}finally{setBusy(false)}}
 async function saveComponent(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setNotice("");try{const f=componentForm;await fetchApi("/reliability/components",{method:"POST",body:JSON.stringify({...f,position_number:f.position_number?Number(f.position_number):null,removed_on:f.removed_on||null,operating_hours_at_install:f.operating_hours_at_install===""?null:Number(f.operating_hours_at_install),operating_hours_at_removal:f.operating_hours_at_removal===""?null:Number(f.operating_hours_at_removal),line_name:f.line_name||null,stand_code:f.stand_code||null,asset_code:f.asset_code||null,component_side:f.component_side||null,serial_number:f.serial_number||null,removal_reason:f.removal_reason||null,condition_on_removal:f.condition_on_removal||null,work_done:f.work_done||null})});setComponentForm(blankComponent());setNotice("Component lifecycle record saved.");await load()}catch(e:any){setError(e.message||"Could not save component")}finally{setBusy(false)}}
 return <div className="dsr-page"><Header title="Reliability Intelligence"/><main className="dsr-main"><div className="full-bleed space-y-4">
 <div className="dsr-section-head"><div><div className="dsr-kicker">Plant-wide reliability agents</div><h1 className="dsr-title">Maintenance & Reliability Intelligence</h1><p className="dsr-subtitle">A searchable, permanent record of breakdowns, inspections, repairs, component changes and life history across all intelligent registers.</p></div></div>
 <div className="grid grid-cols-2 md:grid-cols-4 gap-2"><div className="dsr-stat"><div className="dsr-stat-label">Current installed components</div><div className="dsr-stat-value">{activeComponents.length}</div></div><div className="dsr-stat"><div className="dsr-stat-label">History events</div><div className="dsr-stat-value">{history.length}</div></div><div className="dsr-stat"><div className="dsr-stat-label">Breakdowns</div><div className="dsr-stat-value">{history.filter(e=>e.event_type==="BREAKDOWN").length}</div></div><div className="dsr-stat"><div className="dsr-stat-label">Records needing review</div><div className="dsr-stat-value">{history.filter(e=>e.verification_status==="AI_REVIEW").length}</div></div></div>
 <div className="mechanical-panel p-3 grid grid-cols-1 md:grid-cols-3 gap-3"><label className="text-sm">Intelligent register<select className="input-class mt-1" value={module} onChange={e=>setModule(e.target.value)}>{modules.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm">Line / area<select className="input-class mt-1" value={line} onChange={e=>setLine(e.target.value)}>{["ALL","WRM1","WRM2","WRM3","W1","W2","W3"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm">Search history<input className="input-class mt-1" value={query} onChange={e=>setQuery(e.target.value)} placeholder="GB failure, stand 3, leakage…"/></label></div>
 <section className="mechanical-panel overflow-hidden"><div className="dsr-panel-head"><div><div className="section-title">AI maintenance message intake</div><div className="helper-text">Paste a WhatsApp shift message, breakdown note or maintenance report. The AI only drafts records; confirmation is required to save.</div></div></div><div className="p-4"><textarea className="input-class min-h-[130px]" value={message} onChange={e=>setMessage(e.target.value)} placeholder={"Example: 12/10/2026 WRM2 stand 3 GB side coupler changed due to play. Gearbox oil leakage observed; seal replaced. Trial run satisfactory."}/><div className="mt-3 flex flex-wrap items-center gap-2"><button className="dsr-btn-primary" disabled={busy||!message.trim()} onClick={analyse}>{busy?"Working…":"Analyse with AI"}</button>{provider&&<span className="dsr-chip">{provider}</span>}<span className="helper-text">No automatic root-cause assumptions. Missing dates must be entered before verified saving.</span></div></div></section>
 {(events.length>0||components.length>0)&&<section className="mechanical-panel overflow-hidden"><div className="dsr-panel-head"><div><div className="section-title">Review AI extraction</div><div className="helper-text">Edit uncertain fields. Confirmed causes should only be entered when supported by evidence.</div></div><button className="dsr-btn-primary" disabled={busy} onClick={confirm}>Confirm & save records</button></div>
 {events.map((x,i)=><div key={"e"+i} className="border-b border-slate-800 p-4 space-y-3"><div className="flex items-center justify-between gap-2"><b className="text-white">Event {i+1}: {x.event_type||"OTHER"}</b><span className="dsr-chip">Confidence {Math.round((x.ai_confidence||0)*100)}%</span></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-2">
 <Field label="Event date / time"><input type="datetime-local" className="input-class" value={x.event_at||""} onChange={e=>patchEvent(i,"event_at",e.target.value)}/></Field>
 <Field label="Line"><input className="input-class" value={x.line_name||""} onChange={e=>patchEvent(i,"line_name",e.target.value)}/></Field>
 <Field label="Position"><input type="number" className="input-class" value={x.position_number??""} onChange={e=>patchEvent(i,"position_number",e.target.value?Number(e.target.value):null)}/></Field>
 <Field label="Stand code"><input className="input-class" value={x.stand_code||""} onChange={e=>patchEvent(i,"stand_code",e.target.value)}/></Field>
 <Field label="Equipment / asset"><input className="input-class" value={x.equipment||""} onChange={e=>patchEvent(i,"equipment",e.target.value)}/></Field>
 <Field label="Component"><select className="input-class" value={x.component_type||"OTHER"} onChange={e=>patchEvent(i,"component_type",e.target.value)}>{componentTypes.map(t=><option key={t}>{t}</option>)}</select></Field>
 <Field label="Event type"><select className="input-class" value={x.event_type||"OTHER"} onChange={e=>patchEvent(i,"event_type",e.target.value)}>{eventTypes.map(t=><option key={t}>{t}</option>)}</select></Field>
 <Field label="Failure mode"><input className="input-class" value={x.failure_mode||""} onChange={e=>patchEvent(i,"failure_mode",e.target.value)}/></Field>
 <Field label="Symptoms / observations"><textarea className="input-class min-h-[65px]" value={x.symptoms||""} onChange={e=>patchEvent(i,"symptoms",e.target.value)}/></Field>
 <Field label="Suspected cause"><textarea className="input-class min-h-[65px]" value={x.suspected_cause||""} onChange={e=>patchEvent(i,"suspected_cause",e.target.value)}/></Field>
 <Field label="Confirmed cause"><textarea className="input-class min-h-[65px]" value={x.confirmed_cause||""} onChange={e=>patchEvent(i,"confirmed_cause",e.target.value)}/></Field>
 <Field label="Action taken"><textarea className="input-class min-h-[65px]" value={x.action_taken||""} onChange={e=>patchEvent(i,"action_taken",e.target.value)}/></Field>
 <Field label="Part removed"><input className="input-class" value={x.part_removed||""} onChange={e=>patchEvent(i,"part_removed",e.target.value)}/></Field>
 <Field label="Part installed"><input className="input-class" value={x.part_installed||""} onChange={e=>patchEvent(i,"part_installed",e.target.value)}/></Field>
 <Field label="Downtime minutes"><input type="number" className="input-class" value={x.downtime_minutes??""} onChange={e=>patchEvent(i,"downtime_minutes",e.target.value?Number(e.target.value):null)}/></Field>
 </div></div>)}
 {components.map((x,i)=><div key={"c"+i} className="border-b border-slate-800 p-4"><b className="text-white">Component installation {i+1}</b><div className="mt-3 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-2"><Field label="Component type"><select className="input-class" value={x.component_type||"OTHER"} onChange={e=>patchComponent(i,"component_type",e.target.value)}>{componentTypes.map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Line"><input className="input-class" value={x.line_name||""} onChange={e=>patchComponent(i,"line_name",e.target.value)}/></Field><Field label="Position"><input type="number" className="input-class" value={x.position_number??""} onChange={e=>patchComponent(i,"position_number",e.target.value?Number(e.target.value):null)}/></Field><Field label="Installed date"><input type="date" className="input-class" value={x.installed_on||""} onChange={e=>patchComponent(i,"installed_on",e.target.value)}/></Field></div></div>)}
 <div className="p-4"><button className="dsr-btn-primary" disabled={busy} onClick={confirm}>Confirm & save records</button></div></section>}
 {notice&&<div className="rounded-lg border border-emerald-900 bg-emerald-950/20 p-3 text-sm text-emerald-200">{notice}</div>}{error&&<div className="rounded-lg border border-red-900 bg-red-950/20 p-3 text-sm text-red-300">{error}</div>}
 <section className="mechanical-panel overflow-hidden"><div className="dsr-panel-head"><div><div className="section-title">Installed component register & life</div><div className="helper-text">Life in days is calculated from install to removal, or today for currently installed items. Operating-hour life is calculated only when both meter readings are known.</div></div></div><div className="dsr-table-wrap border-0 rounded-none"><table className="dsr-table min-w-[1050px]"><thead><tr>{["Register","Line / position","Component","Side / serial","Installed","Removed","Life days","Life hours","Removal reason","Status"].map(x=><th className="dsr-th" key={x}>{x}</th>)}</tr></thead><tbody>{shownComponents.map(c=><tr key={c.id}><td className="dsr-td">{c.module_code}</td><td className="dsr-td">{c.line_name||"—"} / {c.position_number??"—"}<div className="helper-text">{c.stand_code||""}</div></td><td className="dsr-td font-semibold">{c.component_type.replaceAll("_"," ")}</td><td className="dsr-td">{c.component_side||"—"}<div className="helper-text">{c.serial_number||c.asset_code||""}</div></td><td className="dsr-td whitespace-nowrap">{c.installed_on}</td><td className="dsr-td whitespace-nowrap">{c.removed_on||"—"}</td><td className="dsr-td">{c.life_days??"—"}</td><td className="dsr-td">{c.observed_life_hours!=null?c.observed_life_hours:"Not enough meter readings"}</td><td className="dsr-td">{c.removal_reason||"—"}</td><td className="dsr-td">{c.removed_on?"REMOVED":"INSTALLED"}</td></tr>)}{!shownComponents.length&&<tr><td colSpan={10} className="dsr-empty">No component installation history for this filter. Add an installation below.</td></tr>}</tbody></table></div></section>
 <section className="mechanical-panel overflow-hidden"><div className="dsr-panel-head"><div><div className="section-title">Record component installation / replacement</div><div className="helper-text">Use a separate row for each physical installation. On replacement, close the old component record and add the new one.</div></div></div><form onSubmit={saveComponent} className="p-4 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
 <Field label="Register"><select className="input-class" value={componentForm.module_code} onChange={e=>setComponentForm({...componentForm,module_code:e.target.value})}>{modules.filter(x=>x!=="ALL").map(x=><option key={x}>{x}</option>)}</select></Field>
 <Field label="Line"><input className="input-class" value={componentForm.line_name} onChange={e=>setComponentForm({...componentForm,line_name:e.target.value})} placeholder="WRM1"/></Field>
 <Field label="Position"><input type="number" min="1" className="input-class" value={componentForm.position_number} onChange={e=>setComponentForm({...componentForm,position_number:e.target.value})}/></Field>
 <Field label="Stand code"><input className="input-class" value={componentForm.stand_code} onChange={e=>setComponentForm({...componentForm,stand_code:e.target.value})}/></Field>
 <Field label="Component"><select className="input-class" value={componentForm.component_type} onChange={e=>setComponentForm({...componentForm,component_type:e.target.value})}>{componentTypes.map(t=><option key={t}>{t}</option>)}</select></Field>
 <Field label="Side"><select className="input-class" value={componentForm.component_side} onChange={e=>setComponentForm({...componentForm,component_side:e.target.value})}><option value="">Not specified</option><option value="MOTOR_SIDE">Motor side</option><option value="GB_SIDE">Gearbox side</option><option value="TOP">Top</option><option value="BOTTOM">Bottom</option><option value="LEFT">Left</option><option value="RIGHT">Right</option></select></Field>
 <Field label="Asset / serial number"><input className="input-class" value={componentForm.asset_code} onChange={e=>setComponentForm({...componentForm,asset_code:e.target.value})} placeholder="Tag or serial"/></Field>
 <Field label="Installed date"><input required type="date" className="input-class" value={componentForm.installed_on} onChange={e=>setComponentForm({...componentForm,installed_on:e.target.value})}/></Field>
 <Field label="Removed date (if removed)"><input type="date" className="input-class" value={componentForm.removed_on} onChange={e=>setComponentForm({...componentForm,removed_on:e.target.value})}/></Field>
 <Field label="Operating hours at install"><input type="number" min="0" className="input-class" value={componentForm.operating_hours_at_install} onChange={e=>setComponentForm({...componentForm,operating_hours_at_install:e.target.value})}/></Field>
 <Field label="Operating hours at removal"><input type="number" min="0" className="input-class" value={componentForm.operating_hours_at_removal} onChange={e=>setComponentForm({...componentForm,operating_hours_at_removal:e.target.value})}/></Field>
 <Field label="Reason removed"><input className="input-class" value={componentForm.removal_reason} onChange={e=>setComponentForm({...componentForm,removal_reason:e.target.value})}/></Field>
 <Field label="Condition on removal"><input className="input-class" value={componentForm.condition_on_removal} onChange={e=>setComponentForm({...componentForm,condition_on_removal:e.target.value})}/></Field>
 <Field label="Work done"><input className="input-class" value={componentForm.work_done} onChange={e=>setComponentForm({...componentForm,work_done:e.target.value})}/></Field>
 <div className="lg:col-span-4"><button className="dsr-btn-primary" disabled={busy}>Save component lifecycle</button></div>
 </form></section>
 <section className="mechanical-panel overflow-hidden"><div className="dsr-panel-head"><div><div className="section-title">Ask the Reliability Agent</div><div className="helper-text">Ask whether a failure happened before, what was changed, what was confirmed, and which evidence supports the answer.</div></div></div><div className="p-4"><textarea className="input-class min-h-[80px]" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="e.g. Has WRM2 position 3 had gearbox leakage before? What parts were changed and when?"/><div className="mt-2"><button className="dsr-btn-primary" disabled={busy||!question.trim()} onClick={askAgent}>{busy?"Investigating…":"Investigate history"}</button></div>{answer&&<div className="mt-3 rounded-lg border border-slate-700 bg-slate-900/70 p-4"><div className="font-semibold text-white">Evidence-based answer</div><p className="mt-2 whitespace-pre-wrap text-sm text-slate-200">{answer}</p><div className="helper-text mt-3">Matched stored records: {answerSources.length}. Answers depend on the history entered in the register; no matching history means the agent cannot confirm a past event.</div>{answerSources.length>0&&<details className="mt-2"><summary className="cursor-pointer text-xs text-slate-400">View source records</summary><div className="mt-2 space-y-2">{answerSources.map((x,i)=><div key={i} className="rounded-md border border-slate-800 p-2 text-xs text-slate-300"><b>{x.date||"Date unknown"} · {x.register} · {x.line||"Line?"} / position {x.position??"?"}</b><div>{x.component||x.equipment||x.event||"Maintenance event"} — {x.failure||x.symptoms||x.action||"No details"}</div><div>{x.action||""}</div></div>)}</div></details>}</div>}</div></section>
 <section className="mechanical-panel overflow-hidden"><div className="dsr-panel-head"><div><div className="section-title">Breakdown & maintenance history</div><div className="helper-text">{shownHistory.length} matching events. Search symptoms, components, line/stand and actions to learn from previous failures.</div></div></div><div className="divide-y divide-slate-800">{shownHistory.map(e=><article key={e.id} className="p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><div className="font-semibold text-white">{e.failure_mode||e.event_type.replaceAll("_"," ")} · {e.component_type?.replaceAll("_"," ")||e.equipment||"Equipment not specified"}</div><div className="helper-text mt-1">{fmt(e.event_at)} · {e.module_code} · {e.line_name||"Line unknown"} · Position {e.position_number??"?"} · Stand {e.stand_code||"?"}</div></div><span className="dsr-chip">{e.verification_status||"VERIFIED"}</span></div>{e.symptoms&&<p className="mt-2 text-sm text-slate-300"><b>Observed:</b> {e.symptoms}</p>}{e.suspected_cause&&<p className="mt-1 text-sm text-amber-200"><b>Suspected cause:</b> {e.suspected_cause}</p>}{e.confirmed_cause&&<p className="mt-1 text-sm text-emerald-200"><b>Confirmed cause:</b> {e.confirmed_cause}</p>}{e.action_taken&&<p className="mt-1 text-sm text-slate-300"><b>Action:</b> {e.action_taken}</p>}{(e.part_removed||e.part_installed)&&<p className="mt-1 text-sm text-slate-400">Parts: {e.part_removed||"—"} → {e.part_installed||"—"}</p>}{e.ai_summary&&<p className="mt-2 rounded-lg bg-slate-900 p-2 text-sm text-slate-300">{e.ai_summary}</p>}{e.source_text&&<details className="mt-2"><summary className="cursor-pointer text-xs text-slate-500">Original source message</summary><p className="mt-2 whitespace-pre-wrap text-xs text-slate-400">{e.source_text}</p></details>}</article>)}{!shownHistory.length&&<div className="dsr-empty">No reliability events saved for this register yet. Paste a maintenance message above to start building searchable history.</div>}</div></section>
 </div></main></div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm"><span>{label}</span><div className="mt-1">{children}</div></label>}
