"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import Header from "@/components/layout/Header";
import { fetchApi } from "@/lib/api";

type Config={lines:Record<string,string[]>;total_running:number};
type Asset={id:number;asset_code:string;name:string;asset_type:string;position?:string|null;installation_date?:string|null;status:string;operating_hours:number;is_running:boolean};
type Life={id:number;line_name?:string|null;position_number?:number|null;stand_code?:string|null;component_type:string;component_side?:string|null;installed_on:string;removed_on?:string|null;life_days:number;observed_life_hours?:number|null};
const components=["STAND","ROLL","ENTRY_GUIDE","GEARBOX","GB","MOTOR","FLOATING_SHAFT","COUPLER","COUPLER_MOTOR_SIDE","COUPLER_GB_SIDE","BEARING","OIL_SEAL","SLEEVE","SHAFT"];
const label=(s:string)=>s.replaceAll("_"," ");
const date=(s?:string|null)=>s?new Date(s).toLocaleDateString():"Not recorded";
export default function RMIRStandAreaPage(){
 const [config,setConfig]=useState<Config|null>(null);const [assets,setAssets]=useState<Asset[]>([]);const [life,setLife]=useState<Life[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [c,a,l]=await Promise.all([fetchApi("/assets/running-config/RMIR"),fetchApi("/assets/RMIR"),fetchApi("/reliability/components?module=RMIR")]);setConfig(c);setAssets(a.assets||[]);setLife(l.components||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load RMIR Stand Area")}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const active=life.filter(x=>!x.removed_on);
 return <div className="dsr-page"><Header title="RMIR · Stand Area"/><main className="dsr-main"><div className="full-bleed space-y-4">
 <div className="dsr-section-head"><div><div className="dsr-kicker">Roughing Mill Intelligent Register</div><h1 className="dsr-title">Stand Area</h1><p className="dsr-subtitle">WRM1–WRM3 stand lineup, linked asset records and current component installation history.</p></div><div className="flex gap-2"><button onClick={load} className="dsr-btn">Refresh</button><Link href="/reliability?module=RMIR" className="dsr-btn-primary">Update components ↗</Link></div></div>
 {error&&<div className="rounded-lg border border-red-900 bg-red-950/30 p-3 text-sm text-red-300">{error}</div>}
 <div className="grid grid-cols-2 md:grid-cols-4 gap-2"><div className="dsr-stat"><div className="dsr-stat-label">Configured running stands</div><div className="dsr-stat-value text-emerald-300">{config?.total_running??0}</div></div><div className="dsr-stat"><div className="dsr-stat-label">Registered RMIR assets</div><div className="dsr-stat-value">{assets.length}</div></div><div className="dsr-stat"><div className="dsr-stat-label">Installed component records</div><div className="dsr-stat-value">{active.length}</div></div><div className="dsr-stat"><div className="dsr-stat-label">Missing component records</div><div className="dsr-stat-value">{Math.max(0,(config?.total_running??15)*components.length-active.length)}</div></div></div>
 {loading?<div className="mechanical-panel p-8 text-center text-slate-400">Loading live RMIR records…</div>:Object.entries(config?.lines||{}).map(([line,codes])=><section key={line} className="mechanical-panel overflow-hidden"><div className="px-4 py-3 border-b border-slate-800 flex items-center justify-between"><div><div className="font-bold text-white">{line}</div><div className="text-xs text-slate-500">Roughing mill running configuration</div></div><span className="text-xs font-bold text-emerald-300">{codes.length} configured</span></div><div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-5 gap-3 p-3">{codes.map((code,index)=>{const rows=active.filter(x=>(x.line_name||"").toUpperCase()===line&&(x.stand_code||"").toUpperCase()===code.toUpperCase());const lineAssets=assets.filter(a=>(a.position||"").toUpperCase()===code.toUpperCase()||(a.asset_code||"").toUpperCase().includes(line+"-"+code));return <article key={code} className="rounded-xl border border-slate-700 bg-[#0B111D] p-3"><div className="flex items-start justify-between"><div><div className="text-[10px] text-slate-500">Position {index+1}</div><div className="text-xl font-black text-white">{code}</div></div><span className="rounded-full border border-emerald-900 px-2 py-1 text-[9px] text-emerald-300">RUNNING</span></div><div className="mt-3 space-y-2">{components.map(type=>{const row=rows.find(x=>x.component_type===type||(type==="COUPLER"&&x.component_type.startsWith("COUPLER")));return <div key={type} className="flex items-start justify-between gap-2 border-t border-slate-800 pt-2 text-xs"><span className="text-slate-400">{label(type)}</span><span className={row?"text-emerald-300 text-right":"text-slate-600 text-right"}>{row?date(row.installed_on):"Not recorded"}</span></div>})}</div>{lineAssets.length>0&&<div className="mt-3 border-t border-slate-800 pt-2 text-[10px] text-slate-500">{lineAssets.length} linked asset record(s)</div>}</article>})}</div></section>)}
 <section className="mechanical-panel p-4"><div className="font-bold text-white">All RMIR component lifecycle records</div><p className="text-xs text-slate-500 mt-1 mb-3">Installed dates and observed life are shown only when recorded. Add missing history rather than assuming dates.</p><div className="dsr-table-wrap"><table className="dsr-table min-w-[850px]"><thead><tr>{["Line","Stand","Component","Side","Installed","Age days","Observed life h","Status"].map(x=><th className="dsr-th" key={x}>{x}</th>)}</tr></thead><tbody>{life.map(x=><tr key={x.id}><td className="dsr-td">{x.line_name||"—"}</td><td className="dsr-td">{x.stand_code||"—"}</td><td className="dsr-td font-semibold">{label(x.component_type)}</td><td className="dsr-td">{x.component_side||"—"}</td><td className="dsr-td">{date(x.installed_on)}</td><td className="dsr-td">{x.life_days??"—"}</td><td className="dsr-td">{x.observed_life_hours??"Meter readings needed"}</td><td className="dsr-td">{x.removed_on?"Removed":"Installed"}</td></tr>)}{!life.length&&<tr><td colSpan={8} className="dsr-empty">No RMIR component lifecycle history yet. Use Update components to enter verified dates and meter readings.</td></tr>}</tbody></table></div></section>
 </div></main></div>
}
