"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import Header from "@/components/layout/Header";
import { fetchApi } from "@/lib/api";

type Life={id:number;line_name?:string|null;stand_code?:string|null;asset_code?:string|null;component_type:string;component_side?:string|null;serial_number?:string|null;installed_on:string;removed_on?:string|null;life_days:number;observed_life_hours?:number|null;removal_reason?:string|null};
type Stock={id:number;name:string;quantity:number;minimum_quantity:number;location:string;used_at?:string|null;expected_life_hours?:number|null;observed_avg_life_hours?:number|null;availability_pct?:number|null;reliability_pct?:number|null;criticality?:string|null};
const label=(s:string)=>s.replaceAll("_"," ");
const date=(s?:string|null)=>s?new Date(s).toLocaleDateString():"—";
export default function RMIRSpareLifePage(){
 const [life,setLife]=useState<Life[]>([]);const [stock,setStock]=useState<Stock[]>([]);const [query,setQuery]=useState("");const [scope,setScope]=useState<"ALL"|"INSTALLED"|"REMOVED">("ALL");const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [l,s]=await Promise.all([fetchApi("/reliability/components?module=RMIR"),fetchApi("/inventory/")]);setLife(l.components||[]);setStock(s||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load RMIR Spare Life")}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const shown=useMemo(()=>life.filter(x=>(scope==="ALL"||(scope==="INSTALLED"&&!x.removed_on)||(scope==="REMOVED"&&!!x.removed_on))&&[x.line_name,x.stand_code,x.asset_code,x.component_type,x.component_side,x.serial_number,x.removal_reason].join(" ").toLowerCase().includes(query.toLowerCase())),[life,query,scope]);
 const low=stock.filter(x=>(x.availability_pct??100)<100).length;
 return <div className="dsr-page"><Header title="RMIR · Spare Life"/><main className="dsr-main"><div className="full-bleed space-y-4">
 <div className="dsr-section-head"><div><div className="dsr-kicker">Roughing Mill Intelligent Register</div><h1 className="dsr-title">Spare Life</h1><p className="dsr-subtitle">Track the service life of installed/replaced RMIR components and view store stock coverage without mixing stock quantity with component lifetime.</p></div><div className="flex gap-2"><button onClick={load} className="dsr-btn">Refresh</button><Link href="/reliability?module=RMIR" className="dsr-btn-primary">Add life / change record ↗</Link></div></div>
 {error&&<div className="rounded-lg border border-red-900 bg-red-950/30 p-3 text-sm text-red-300">{error}</div>}
 <div className="grid grid-cols-2 md:grid-cols-4 gap-2"><div className="dsr-stat"><div className="dsr-stat-label">RMIR life records</div><div className="dsr-stat-value">{life.length}</div></div><div className="dsr-stat"><div className="dsr-stat-label">Currently installed</div><div className="dsr-stat-value text-emerald-300">{life.filter(x=>!x.removed_on).length}</div></div><div className="dsr-stat"><div className="dsr-stat-label">Replaced / removed</div><div className="dsr-stat-value">{life.filter(x=>!!x.removed_on).length}</div></div><div className="dsr-stat"><div className="dsr-stat-label">Store items below target</div><div className="dsr-stat-value text-amber-300">{low}</div></div></div>
 <section className="mechanical-panel p-3"><div className="flex flex-col md:flex-row gap-2"><input className="input-class md:max-w-md" placeholder="Search stand, component, serial or removal reason…" value={query} onChange={e=>setQuery(e.target.value)}/><select className="input-class md:w-auto" value={scope} onChange={e=>setScope(e.target.value as typeof scope)}><option value="ALL">All lifecycle records</option><option value="INSTALLED">Currently installed</option><option value="REMOVED">Removed / replaced</option></select></div></section>
 <section className="mechanical-panel p-4"><div className="font-bold text-white">RMIR component life history</div><p className="text-xs text-slate-500 mt-1 mb-3">Life in days is derived from installation/removal dates. Observed operating life is shown only when install and removal meter readings exist.</p><div className="dsr-table-wrap"><table className="dsr-table min-w-[1000px]"><thead><tr>{["Line","Stand","Component","Side","Serial","Installed","Removed","Life days","Life hours","Removal reason"].map(x=><th className="dsr-th" key={x}>{x}</th>)}</tr></thead><tbody>{shown.map(x=><tr key={x.id}><td className="dsr-td">{x.line_name||"—"}</td><td className="dsr-td">{x.stand_code||"—"}</td><td className="dsr-td font-semibold">{label(x.component_type)}</td><td className="dsr-td">{x.component_side||"—"}</td><td className="dsr-td">{x.serial_number||"—"}</td><td className="dsr-td">{date(x.installed_on)}</td><td className="dsr-td">{date(x.removed_on)}</td><td className="dsr-td">{x.life_days??"—"}</td><td className="dsr-td">{x.observed_life_hours??"Needs meter readings"}</td><td className="dsr-td">{x.removal_reason||"—"}</td></tr>)}{!shown.length&&<tr><td colSpan={10} className="dsr-empty">No matching component records. Add verified installation/removal history through Reliability Intelligence.</td></tr>}</tbody></table></div></section>
 <section className="mechanical-panel p-4"><div className="font-bold text-white">Shared store stock snapshot</div><p className="text-xs text-slate-500 mt-1 mb-3">Stock data is shared with the plant inventory register; only label a spare RMIR-specific in its “Used at” field. These stock quantities are not component life records.</p><div className="dsr-table-wrap"><table className="dsr-table min-w-[850px]"><thead><tr>{["Spare","Used at","Store qty","Required","Availability","Expected life h","Observed avg h","Criticality"].map(x=><th className="dsr-th" key={x}>{x}</th>)}</tr></thead><tbody>{stock.filter(x=>!query||[x.name,x.used_at,x.criticality].join(" ").toLowerCase().includes(query.toLowerCase())).map(x=><tr key={x.id}><td className="dsr-td font-semibold">{x.name}</td><td className="dsr-td">{x.used_at||"Not assigned"}</td><td className="dsr-td">{x.quantity}</td><td className="dsr-td">{x.minimum_quantity}</td><td className="dsr-td">{x.availability_pct==null?"Not assessed":x.availability_pct+"%"}</td><td className="dsr-td">{x.expected_life_hours??"—"}</td><td className="dsr-td">{x.observed_avg_life_hours??"—"}</td><td className="dsr-td">{x.criticality||"Unassessed"}</td></tr>)}{!stock.length&&<tr><td colSpan={8} className="dsr-empty">No stock items have been entered in the shared store register.</td></tr>}</tbody></table></div><div className="mt-3"><Link href="/inventory" className="dsr-btn">Manage shared store stock ↗</Link></div></section>
 </div></main></div>
}
